/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function runYangLintInNonStrictMode(yangLintBinaryLocation: string, yangFiles: Array<string>, networkPath: string): Promise<string>
export declare function runYangLintInStrictMode(yangLintBinaryLocation: string, yangFiles: Array<string>, networkPath: string): Promise<string>
